# Netlify configuration for Next.js McDonald's Malaysia Frontend

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://mcdonalds-malaysia-api.onrender.com"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

# Context-specific settings
[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://mcdonalds-malaysia-api.onrender.com"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://mcdonalds-malaysia-api.onrender.com"

[context.branch-deploy.environment]
  NEXT_PUBLIC_API_URL = "https://mcdonalds-malaysia-api.onrender.com"

# Essential Next.js plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, immutable, max-age=31536000"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API proxy to backend
[[redirects]]
  from = "/api/v1/*"
  to = "https://mcdonalds-malaysia-api.onrender.com/api/v1/:splat"
  status = 200
  force = true

# Client-side routing fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Development settings
[dev]
  port = 8888
  autoLaunch = true
